{{- if .Values.s3.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-backup-config
  labels:
    app.kubernetes.io/name: {{ include "etcd-backup.name" . }}
    helm.sh/chart: {{ include "etcd-backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  S3_ENDPOINT_URL: "{{ .Values.s3.s3EndpointUrl }}"
{{- end }}