{{- if .Values.backup.customPV.enabled }}
{{- if .Values.backup.customPV.useSealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.backup.customPV.secretName }}
  labels:
    app.kubernetes.io/name: {{ include "etcd-backup.name" . }}
    helm.sh/chart: {{ include "etcd-backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  encryptedData:
    username: {{ .Values.backup.customPV.username }}
    password: {{ .Values.backup.customPV.password }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backup.customPV.secretName }}
  labels:
    app.kubernetes.io/name: {{ include "etcd-backup.name" . }}
    helm.sh/chart: {{ include "etcd-backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  username: {{ .Values.backup.customPV.username | b64enc }}
  password: {{ .Values.backup.customPV.password | b64enc }}
{{- end }}
{{- end }}
