{{- if .Values.s3.enabled }}
{{- if .Values.s3.createSecret }}
{{- if .Values.s3.sealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.s3.secretName }}
  labels:
    app.kubernetes.io/name: {{ include "etcd-backup.name" . }}
    helm.sh/chart: {{ include "etcd-backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  encryptedData:
    S3_ACCESS_KEY: {{ .Values.s3.accessKey }}
    S3_SECRET_KEY: {{ .Values.s3.secretKey }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.s3.secretName }}
  labels:
    app.kubernetes.io/name: {{ include "etcd-backup.name" . }}
    helm.sh/chart: {{ include "etcd-backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | b64enc }}
  S3_SECRET_KEY: {{ .Values.s3.secretKey | b64enc }}
{{- end }}
{{- end }}
{{- end }}